// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using student_marking_system.Data;

#nullable disable

namespace student_marking_system.Migrations.ClgDb
{
    [DbContext(typeof(ClgDbContext))]
    [Migration("20260707000000_AttendanceStudentIdString")]
    partial class AttendanceStudentIdString
    {
    }
}
